### ISSUE TITLE
Method not found popup on start

### ISSUE THREAD

**Issue by 304NotModified** [PaulStovell/ServiceBouncer#21]
### Overview

Thanks for this great tool. It works on most machines, but on one I get an error (popup), which I can't explain. 

### Expected Behavior

No error popup

### Actual Behavior

Error popup intermediate after start. It can't list the services. 

### Steps To Reproduce Behavior

1. Start the .exe

2. get this error: 
![image](https://user-images.githubusercontent.com/5808377/30955899-9b963ee0-a435-11e7-9ede-698339be5ad4.png)

--
### System Info

App Version: 1.1.0
Operating System Version: Windows Server 2012 R2

**Comment by 304NotModified** [comment]
Ow I think the issue is here the Framework 4.6.1 requirement. 

I would expected a different error then

**Comment by 304NotModified** [comment]
This could be helpful: https://stackoverflow.com/questions/951856/is-there-an-easy-way-to-check-the-net-framework-version

**Comment by BlythMeister** [comment]
You are correct, the app required 4.6.1 to be installed in order to run.

I've added a framework version check, so you will get a nicer error if you do not have 4.6.1 installed

**Comment by 304NotModified** [comment]
👍 thanks!
