### ISSUE TITLE
ServiceBouncer preventing directories being deleted due to exe access

### ISSUE THREAD

**Issue by robert-berry-15below** [PaulStovell/ServiceBouncer#22]
When attempting to re-deploy a service the directory cannot be deleted as the exe of the program is still in use. Once ServiceBouncer is closed the exe can then be deleted. In the previous 1.0.3 version we were using  this was not an issue

**Comment by BlythMeister** [comment]
Have attempted to reproduce this and i am unable to reproduce it.
My only suggestion is to find out what bit of the application is causing the lock in the environment you are running in.

**Comment by 304NotModified** [comment]
can't repo also, as you sure that the service has been stopped?

**Comment by BlythMeister** [comment]
Closing as unable to repo, can re-open if required.
