### ISSUE TITLE
Remote Connection Log-In

### ISSUE THREAD

**Issue by BlythMeister** [PaulStovell/ServiceBouncer#26]
### Overview

An extension to the completed #16 which allows remote connections.
When use is not able to access the remote machine, prompt them for user credentials to use.

https://stackoverflow.com/a/212673 gives examples on how you can perform user impersonation with a service controller.

### Expected Behavior

When unable to get services due to insufficient permission, prompt user for login details.
Or, when connecting to a machine which is not the local machine, ask user if they need to log in.

### Actual Behavior

If you are unable to view services on remote machine, an error occurs

### Steps To Reproduce Behavior

1. Enter the machine name of a remote machine you do not have permissions to.
2. Error occurs

**Comment by object71** [comment]
I have some experience with impersonation and will grab that when I have the time. Also tested the application and I really need this feature.

The application is great by the way and feels really nice to use it.

**Comment by object71** [comment]
Impersonation didn't turn out that easy - there is a problem impersonation is mainly thread based and there are too many tasks going about in the application.

I tested it with the runas command and it works that way. The one solution I am thinking of is to start a new service bouncer process from this one that would directly connect to the target machine.

**Comment by BlythMeister** [comment]
Huh that's actually quite clever...I didn't think of that 👍
