### ISSUE TITLE
Add configurable service controller timeout

### ISSUE THREAD

**Issue by jawn** [PaulStovell/ServiceBouncer#3]
When restarting a service, the current timeout is fixed to 30 seconds:

> controller.WaitForStatus(ServiceControllerStatus.Stopped, TimeSpan.FromSeconds(30));

It would be helpful to load the timeout from the application config file and/or provide a Setup GUI.

This makes the tool extra useful in cases where the Windows service controller fails to restart due to its hard-coded timeout.

**Comment by 304NotModified** [comment]
+1

**Comment by ruperthawkes** [comment]
+1

**Comment by ruperthawkes** [comment]
Or even better perhaps wait for the period, then check that the service has stopped before attempting to restart

**Comment by BlythMeister** [comment]
Added error message if timeout expired & therefore doesn't try to start but informs you.

Have also increased timeout to 60 seconds.
