### ISSUE TITLE
Service Install/Uninstall Feature

### ISSUE THREAD

**Issue by UgurAldanmaz** [PaulStovell/ServiceBouncer#4]
I think that it can be useful service installing/uninstalling feature. I want to code it, if anyone want it too.
Please tell me your ideas.

**Comment by 304NotModified** [comment]
+1

**Comment by UgurAldanmaz** [comment]
Thank you @304NotModified :)

**Comment by 304NotModified** [comment]
Yeah I think this is a killer feature!

**Comment by UgurAldanmaz** [comment]
Hi @304NotModified. I developed and [made a PR](https://github.com/PaulStovell/ServiceBouncer/pull/9). I hope Mr. Paul will accept it.

**Comment by BlythMeister** [comment]
This has now been implemented
