### ISSUE TITLE
Bug: open service folder won't work for services installed with UNC path

### ISSUE THREAD

**Issue by 304NotModified** [PaulStovell/ServiceBouncer#41]
### Overview

The "open service folder" won't work for services installed with UNC path

### Expected Behavior

open folder with the .exe

### Actual Behavior

opens "this pc" in explorer

### Steps To Reproduce Behavior

- Install service under UNC path, e.g. \\server1\folder\service1.exe"
- do "open service folder"

--
### System Info

App Version: 1.2.7 - note this is also not solved in #40
Operating System Version:  Windows 2012 R2

**Comment by 304NotModified** [comment]
If I have time, I will try to solve it. Let you know when I start on it.

**Comment by BlythMeister** [comment]
@304NotModified is that not fixed by your recent change?

**Comment by 304NotModified** [comment]
> note this is also not solved in #40

;)

nope. Had no time to fix it
