### ISSUE TITLE
Please create a new release - 1.2.8

### ISSUE THREAD

**Issue by 304NotModified** [PaulStovell/ServiceBouncer#43]
Please create a new release - 1.2.8

The fixes since 1.27: #42, #41, #40, #39,

**Comment by BlythMeister** [comment]
on it...it's all manual & i've been away from a machine that can build/release

**Comment by BlythMeister** [comment]
@304NotModified see https://github.com/PaulStovell/ServiceBouncer/releases/tag/1.2.8 :)
