### ISSUE TITLE
Sub par performance whilst idling.

### ISSUE THREAD

**Issue by savstars** [PaulStovell/ServiceBouncer#49]
### Overview

Idle ServiceBouncer consumes a total of about 10% of CPU resources.  From what I can gather, this is caused by the inefficient method of polling the service manager to check to see if there are any updates.

### Expected Behavior

ServiceBouncer.exe should cause <1% CPU usage when Idle.

### Actual Behavior

ServiceBouncers polling incurs ~10% CPU load when idling.  This is spread over ServiceBounce.exe and Services.exe

### Steps To Reproduce Behavior

1. Have at least 50 more services than the default number that are installed with windows server, on hardware with 2 cores or perhaps even 4.

2. Load ServiceBouncer.

3. Leave ServiceBouncer Idle for a few seconds.

4. In task manager, note that the combined CPU usage of ServiceBounce.exe and Services.exe is about 10% of the total CPU load.  

--
### System Info

App Version: _v1.2.10
Operating System Version: WinsServer2008 and WinServer2019

**Comment by BlythMeister** [comment]
This is why service bouncer polling stops when the application loses focus.

If there is a better way to check service statuses then i'm all ears :D

**Comment by savstars** [comment]
Hold my beer...

**Comment by savstars** [comment]
I'm pretty sure my beer would be getting warm by now.  I hope you haven't drunk it @BlythMeister .

My proposed solution is for the ServiceBounce process to respond to events, rather than continuously poll.  The current pull request #50 can be refined a bit, but it works.
