### ISSUE TITLE
Show icons for status

### ISSUE THREAD

**Issue by 304NotModified** [PaulStovell/ServiceBouncer#8]
Feature request: show icons instead of Running, Stopped etc. This IMO more readable. 

In datagrid & contextmenu. 

![image](https://cloud.githubusercontent.com/assets/5808377/11528855/a1052caa-98e9-11e5-97e1-653b20b529b2.png)

**Comment by BlythMeister** [comment]
![image](https://user-images.githubusercontent.com/1046836/30703092-a39dd2aa-9ee6-11e7-83d8-04ffa46fa5e5.png)

Added as part of next release
